Dk/feature
noahallen/Avalon pull request #51
Opened 2024-03-16 22:51 UTC by ayredkklc

2024-03-22 22:25 UTC, pzjiang commented
github trolled me

2024-03-23 21:25 UTC, noahallen requested changes

2024-03-23 21:25 UTC, noahallen commented on src/components/table.js
> +import { click } from "@testing-library/user-event/dist/click.js";
This is unused.

2024-03-23 21:25 UTC, noahallen commented on src/components/GameProvider.js
> +	const [isDebugFlag, setIsDebugFlag] = useState(true);
We should commit this with false.

2024-03-23 21:25 UTC, noahallen commented on src/firebase/api.jsx
> +			};
Delete unused comments

2024-03-23 21:25 UTC, noahallen commented on src/firebase/api.jsx
> +	} = await get(child(dbref, roundPath)).then((snapshot) => {
Delete

2024-03-23 21:25 UTC, noahallen commented on src/firebase/api.jsx
> +	*/
Delete

2024-03-23 21:25 UTC, noahallen commented on src/pages/MainGamePage.jsx
> +		setShowVotes(true); // Close "Votes" popup
Comment here seems wrong

2024-03-23 21:33 UTC, noahallen approved these changes

2024-03-23 21:33 UTC, merged